name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Packages
      run: npm ci
    - name: Check Commit Message
      run: | 
        echo "${{github.event.head_commit.message}}" > commit.msg
        cat commit.msg | npx commitlint -g commitlint.config.js
        rm commit.msg
    - name: "Get Next Version"
      id: semver
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        dry_run: true
    - name: Set .Net Version
      uses: cdotyone/github-set-net-version@master
      with:
        version: "${{ steps.semver.outputs.new_version }}"
      run: npm install
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '2.2.108'
    - name: Install Nuget Dependencies
      run: dotnet restore
    - name: Build .NET
      run: dotnet build --configuration Release --no-restore
    - name: Conventional Changelog
      uses: vemel/update-changelog@0.0.1
      run: npm install
      with:
        version: ${{ steps.semver.outputs.new_version }}
    - name: Tag
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}