name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Packages
      run: npm ci
    - name: Check Commit Message
      run: echo "${{github.event.head_commit.message}}" > commit.msg; cat commit.msg | npx commitlint -g commitlint.config.js; rm commit.msg
    - name: "Get Next Version"
      id: semver
      uses: cdotyone/github-next-version@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        REVISION: "${{JSON.stringify(github.event.head_commit)}}"
    - name: Set .Net Version
      uses: cdotyone/github-set-net-version@master
      with:
        version: ${{ steps.semver.version }}
    - name: Upload VERSION
      uses: actions/upload-artifact@v1
      with:
        name: version
        path: VERSION
